### ISSUE TITLE
Doesn't work with Django 1.8 updates

### ISSUE THREAD

**Issue by juanandresgs** [kevthehermit/YaraManager#1]
Hi!

A couple of issues: since the change from commit_on_success to atomic() can't upload rules anymore
A crude attempt to fix this by replacing w/ atomic, leads to issues with the new parsing of urls(). Changing urlpatterns to the new format breaks the url regex and I haven't been able to fix it.

Would love to use this project if it can be fixed :)

**Comment by philpraxis** [comment]
+1
Django-1.8.18
Oh... i've just seen this issue was opened one year ago! :/

**Comment by matandobr** [comment]
@juanandresgs @philpraxis 
I know this is an old thread, but you can use my python3 fork if you still need it
